name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Change this to the main branch name if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone the target repository
        run: git clone https://github.com/openstreamorg/openstreammusic target-repo

      - name: Publish GitHub Pages
        run: |
          cd target-repo
          cp -R app/* .
      
      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: .
